plugins:
  eslint:
    enabled: true

checks:
  argument-count:
    config:
      threshold: 5

exclude_patterns:
  - config/
  - '**/node_modules/'
  - '**/*.test.js'
  - 'docs/'
  - 'packages/**/dist'
  - rollup.config.js
  - babel.config.js
